### ISSUE TITLE
Missing CTA-PROD4-pmt_MAGIC[12]_test.cfg

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/lst-sim-config#12]
It seems that sim_telarray branch is missing the PMT config files:
CTA-PROD4-pmt_MAGIC1_test.cfg
CTA-PROD4-pmt_MAGIC2_test.cfg

EDIT: 
also other files are missing:
LightCollection-MAGIC2-smooth_simtel.dat
camera_CTA-MAGIC_MajorityTrigger-3NN.dat
mirror_CTA-MAGIC1_new_corrected-mirror-positions.dat
mirror_CTA-MAGIC2_new_corrected-mirror-positions.dat
prompt_ap-M1.dat 
prompt_ap-M2.dat
qe-hamamatsu_M1_koji.dat
qe-hamamatsu_M2_koji.dat
ref_M1_average.dat 
ref_M2_average.dat

**Comment by YoshikiOhtani** [comment]
Hi, I have just pushed the files directly to the sim-telarray branch
