### ISSUE TITLE
Use mirror_degraded_reflection to simulate lower telescope efficiency

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/lst-sim-config#23]
Instead of telescope_transmission, which should be used only to account for the shadowing caused by the telescope structure.

**Comment by moralejo** [comment]
@voutsi, @mexanick, @jsitarek: Konrad informed us that there is a parameter `mirror_degraded_reflection`, that is the right one to use to simulate a lower mirror reflectivity (or light losses anywhere else as determined e.g. from comparison of observed and simulated muon events).

So following the discussion in #6, I propose to use the following value **for LST-1** in the first sim_telarray production:

```
telescope_transmission 0.9690
mirror_degraded_reflection 0.784
```

0.784 comes from the original factor in the previous production (0.80, from muon ring analysis) and the 2% reduction in the calibrated charges (which affects only real data) that came with lstchain v>=0.8.  It is just  0.80 * 0.98 = 0.784

In any case, we will re-do the muon ring analysis with the new MC (and different datasets) and we will revise this setting.

Remember also that the reference Crab observations are from late 2020 (where about 5% of the LST1 mirrors were defocused) - hence for the LSTs in the next CTA official production we have suggested to increase the value considering that 5% difference.

Note that sim_telarray will scale down the NSB rate by the factor `mirror_degraded_reflection` (which is fine, since the value for the dark NSB rate came from a calculation assuming "100%" efficiency, and not an empirical value obtained from the actual LST1 camera)

**Comment by maxnoe** [comment]
This was done as far as I can see
