### ISSUE TITLE
MAGIC2  single p.e. spectrum

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/lst-sim-config#37]
I checked in the past the SPE of MAGIC1 and it looked fine. While investigating some problem with recovering the proper number of p.e. from calibration run in M2 I realized that I did not check it for M2, and it is actually not matching at all. 
![spe_comparison](https://user-images.githubusercontent.com/33022433/160907582-6f37e40e-9e74-44bc-a0f4-18505576c6be.png)

In MagicSoft simulation the same SPE is used for M1 and M2, however in sim_telarray SPE is given in the same file with the afterpulses distribution, and this one is somewhat different for M1 and M2 in MagicSoft. 
I will fix it, but I need to recompute the AP as well, @moralejo @Voutsi please wait with this rerunning of the sim_telarray until I do so

**Comment by rlopezcoto** [comment]
Hi Julian
> is somewhat different for M1 and M2 in MagicSoft.

you mean it is different for M1 and M2 in `simtelarray`, right? does anybody know why they were defined differently for M1 and M2 when they were implemented?

**Comment by jsitarek** [comment]
No @rlopezcoto , I really mean in MagicSoft. SPE is the same, but AP are different in MagicSoft (this might have to do with the age of the camera, afterpulses change with time, or with some differences in PMT productions. 
in sim_telarray both SPE and AP are given in one file, and this is why SPE had to be specified also separately (the binning of AP is also somewhat different between M1 and M2, that further complicated the issue

**Comment by jsitarek** [comment]
closing the issue, since the fix is already merged
