### ISSUE TITLE
LST1 optical PSF simulation update 

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/lst-sim-config#5]

**Comment by jurysek** [comment]
Below you can find simtel parameters reproducing PSF of LST-1 from 20th November 2020. If we won't manage to get any average value soon, I would suggest using these (or slightly lower as we can smear PSF in later stages of the analysis).

mirror_align_random_horizontal=0.0052,28.,0.0,0.0 
mirror_align_random_vertical=0.0056,28.,0.0,0.0
[psf_tuning.pdf](https://github.com/cta-observatory/lst-sim-config/files/7710964/psf_tuning.pdf)

**Comment by satoshifukami0115** [comment]
Hi, here I show the recent study on the best possible PSF by overlapped mirror-wise images.
I think p8 is the best one possible (D80: 31mm).

[LSTOptics_PSF_from_mirror_wise_images.pdf](https://github.com/cta-observatory/lst-sim-config/files/7711193/LSTOptics_PSF_from_mirror_wise_images.pdf)

This is preliminary and we still need to understand the discrepancy with the previous simulations (D80: 20-28 mm, I actually don't know how they are produced), but we can already start to adjust the simtel parameters to this result.

@jurysek I think we can make the two parameters (`mirror_align_random_horizontal` and `mirror_align_random_vertical`) smaller. It is also better considering we can worsen PSF by the software later.
Could you do it? Also we might have to compare not only D80 but also light containment curves from the spot center.

**Comment by moralejo** [comment]
Thanks, @jurysek and @satoshifukami0115. 
I agree that we should try to adjust the light containment curve, can you give it a try, @jurysek ?

**Comment by jurysek** [comment]
Thanks @satoshifukami0115 ! Find below some plots for simulation of a star in sim_telarray at 20 deg zenith angle. Here I didn't consider asymmetry of the PSF and set both relevant parameters equal (`mirror_align_random_horizontal` and `mirror_align_random_vertical`). You can see that to get D80=30.9mm, we should set these parameters to **0.0046**.

I can also compare the cumulative distributions with those provided by @satoshifukami0115 , and also his ray-tracing simulations with the star simulations in simtel, but to do that I would need the raw images/data. @satoshifukami0115 could you provide me with those? Unfortunately, I cannot promise I will make it by Friday..

Also considering the spread of the D80-mirror_align_random_* plot and the fluctuations in the cumulative distributions, I think I should produce larger sample of simulated photons before we decide to simulate asymmetric PSF in the new MC production.

![D80](https://user-images.githubusercontent.com/32541111/146065170-1659bacf-f30a-426c-81dd-9d5f14c7287c.png)
![psf_cumulative](https://user-images.githubusercontent.com/32541111/146065190-1c1ff1ea-b975-4b18-8baa-4210244a0aea.png)

**Comment by satoshifukami0115** [comment]
> I can also compare the cumulative distributions with those provided by @satoshifukami0115 , and also his ray-tracing simulations with the star simulations in simtel, but to do that I would need the raw images/data. @satoshifukami0115 could you provide me with those? Unfortunately, I cannot promise I will make it by Friday..

@jurysek thank you! The following is the text file including the radius vs the cumulative fraction.
Please let me know if the format is OK for you.
[LightCumulativeCurve.txt](https://github.com/cta-observatory/lst-sim-config/files/7714541/LightCumulativeCurve.txt)

But it looks already similar between the curve 0.0046 (pink) and p8 of the slide I sent above.

**Comment by jurysek** [comment]
Thank you @satoshifukami0115 ! Here is the comparison. The '0.0046 cumulative distribution' is close to yours indeed. 

But if we want to consider also PSF asymmetry, I would need the data which you used to plot the 2D PSF (left Figure in slide 8). However, provided that we have quite a good agreement even now, I am not really sure whether it is worth it at this point. Maybe introducing more complexity in the simtel configuration would be contraproductive.. @moralejo what do you think?

![psf_cumulative](https://user-images.githubusercontent.com/32541111/146079481-36a8d356-3d3a-4acb-9dd4-eb9b6cd6fe0e.png)

**Comment by moralejo** [comment]
Thanks @jurysek, and I agree: I would not introduce now the asymmetry. 
Could you overlay the same curve for the previous simulation settings, for comparison?

**Comment by jurysek** [comment]
@moralejo Both parameters in the previous simtel production were set to 0.0039 and I simulated a star from 0.003 with 0.0002 increments, so I added 0.0038 and 0.0040 in the plot for comparison. The differences are quite small and interestingly the original configuration represents core of the PSF better. In the tail, however, the new one gives better match. 

D80 (0.0038) = 28.733 mm
D80 (0.0040) = 29.805 mm
D80 (0.0046) = 31.220 mm

![psf_cumulative](https://user-images.githubusercontent.com/32541111/146164048-cead1df8-f914-4b48-b524-458bb8e2b864.png)

**Comment by moralejo** [comment]
Thanks, interesting!  The differences of the light within a pixel (D=50 mm) are really small. Given the pixel size, I would inded go for 0.0046, which matches better from D=25mm.

One thing that intrigues me is that the tuning you @jurysek did to the Nov'20 data was (0.0052, 0.0056), which resulted in D80=32.7 mm. I think the tuning at the DL1b level (to match the muon rings) was stronger, as much as 12.5% of the light in one pixel was redistributed. And indeed, the gamma image Width distribution (see your file psf_tuning.pdf above) that you obtain is still shifted left (lower values) compared to the data's. Perhaps there is a discrepancy (MC vs. data) in the focusing of the telescope for shower observation? And hence by tuning psf on star images taken with focus @ infinity we don't manage to match the showers or the muons?

**Comment by jurysek** [comment]
> Perhaps there is a discrepancy (MC vs. data) in the focusing of the telescope for shower observation? And hence by tuning psf on star images taken with focus @ infinity we don't manage to match the showers or the muons?

It definitely could be. It was also proposed by Konrad, when we discussed why I am getting much better MC-data match at DL2 level using much larger PSF than the one we got from star measurement. It finally turned out as a false clue, but it may still be valid at least to some extent.

But still, if we the goal is to set the PSF in simtel 'slightly better' than we see in the data, then 0.0046 should be fine, as we can do the rest of the tuning at DL1b level.

**Comment by moralejo** [comment]
From my side, I bless 0.0046

**Comment by satoshifukami0115** [comment]
From the AMC team, there are no objections so far to provide the D80 (31 mm) & the light containment curve.

We have to investigate the discrepancy with the ray-trace simulations in the past, but it would be more realistic to use this value instead of the simulation values.

We will let you know in case we have any additional suggestions.

**Comment by moralejo** [comment]
> From the AMC team, there are no objections so far to provide the D80 (31 mm) & the light containment curve.
> 
> We have to investigate the discrepancy with the ray-trace simulations in the past, but it would be more realistic to use this value instead of the simulation values.
>
Hi @satoshifukami0115, can you clarify? Do you agree with using the 0.0046 setting above, or will you provide a different curve in the coming days?

**Comment by satoshifukami0115** [comment]
@moralejo We agreed that we use the current curve/D80 as the best-possible real PSF. Sorry for the confusing expression.

I have a little concern that the cherenkov lights typically have off-axis angles and the PSF becomes larger, but I think it is still OK to go for 0.0046 to match the tail side of the curve, as even 1 deg off-axis light might have D80 ~50 mm (~1 pixel size) with this setting.

So I agree on 0.0046 for `mirror_align_random_horizontal` and `mirror_align_random_vertical`.

**Comment by moralejo** [comment]
> 
> I have a little concern that the cherenkov lights typically have off-axis angles and the PSF becomes larger, but I think it is still OK to go for 0.0046 to match the tail side of the curve, as even 1 deg off-axis light might have D80 ~50 mm (~1 pixel size) with this setting.

The main reason for this is coma aberration, which is naturally simulated, so I don't think that is a problem at all. If anything, I think it would make the small on-axis differences less relevant.

> 
> So I agree on 0.0046 for `mirror_align_random_horizontal` and `mirror_align_random_vertical`.

ok, thanks!

**Comment by satoshifukami0115** [comment]
> The main reason for this is coma aberration, which is naturally simulated, so I don't think that is a problem at all. If anything, I think it would make the small on-axis differences less relevant.

OK, thank you. Maybe I was just confused. If we match on-axis PSF between real and simulation, off-axis PSF should also be matched naturally. Even if there is a discrepancy (on either side of D > 25 mm or D < 25 mm of the curve), the aberration makes it less relevant for off-axis cases.

Again let me agree on this value (0.0046).

**Comment by nodak031027** [comment]
ok the members here agreed on 0.0046. I think it is fine. 
Also, the ideal (software) alignment gives us 30.9, while the 0.0046 gives 31.2, right? It sounds realistic as well to me.
