### ISSUE TITLE
small test file for lstchain unit tests

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/lst-sim-config#51]
Hi,

To make sure lstchain works properly with simulations made using the config here, it would be great if we could produce a small test file that contains a small number of triggered events.

I would propose the following (to make sure the file is small enough but contains nice events for testing):

* gamma-diffuse
* 10 events
* viewcone 2°
* energy range (maybe 100 GeV to 5 TeV)
* impact range 250 m

**Comment by Voutsi** [comment]
Hi @maxnoe 

please find the simtel file here:
/home/georgios.voutsinas/ws/AllSky/TestFile

**Comment by maxnoe** [comment]
@Voutsi any reason it is stil gzipped and not zstd?

**Comment by Voutsi** [comment]
No reason. Since we set up the pipeline of MC production and process, I decided not to change it

**Comment by maxnoe** [comment]
Seems the file has a lot more than ten events..., ah, reuse is not 1?

Maybe it's fine, the file is not too large...

**Comment by Voutsi** [comment]
Yes, reuse is 10... 

> Maybe it's fine, the file is not too large...

The file is very fast to produce, let me know if you need a smaller one
