### ISSUE TITLE
 MC generation request: ST0320 for dec_4822 line

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/lst-sim-config#57]
settings: ST0320

train line: dec_4822

test nodes:
node_theta_57.995_az_327.238_
node_theta_35.904_az_17.462_
node_theta_52.41_az_327.619_
node_theta_55.944_az_327.23_
node_theta_55.25_az_327.264_
node_theta_35.904_az_342.538_
node_theta_32.059_az_355.158_
node_theta_49.458_az_328.397_
node_theta_39.646_az_335.667_
node_theta_56.633_az_327.214_
node_theta_43.113_az_331.977_
node_theta_46.37_az_329.754_
node_theta_59.336_az_327.329_

**Comment by Voutsi** [comment]
Hi @jsitarek , this production is ready. The test nodes can be found at:

/fefs/aswg/data/mc/DL0/LSTProd2/TestDataset/sim_telarray/ST0320

while the training dataset:

/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/ST0320

and correspondingly for diffuse gammas

**Comment by jsitarek** [comment]
I finished with processing those files, they are available in:
/fefs/aswg/LST1MAGIC/mc/.../ST0320A/NSB.../v01.3/dec_4822
