### ISSUE TITLE
MC generation request: M20318 for dec_2276 line

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/lst-sim-config#58]
settings: M20318
Note that those are still not tagged!

train line: dec_2276

test nodes:
node_theta_43.197_az_87.604_
node_theta_52.374_az_110.312_
node_theta_14.984_az_175.158_
node_theta_37.814_az_90_
node_theta_10.0_az_248.117_
node_theta_32.059_az_248.099_
node_theta_23.630_az_100.758_
node_theta_52.374_az_301.217_
node_theta_10.0_az_102.199_
node_theta_47.952_az_90_
node_theta_43.197_az_262.712_
node_theta_52.374_az_49.119_
node_theta_32.059_az_102.217_
node_theta_37.814_az_270_
node_theta_23.630_az_259.265_
node_theta_52.374_az_240.004_
node_theta_47.952_az_270_

**Comment by jsitarek** [comment]
the release of sim_telarray settings for this M20318 period is ready:
https://github.com/cta-observatory/lst-sim-config/releases/tag/sim-tel_LSTProd2_MAGICM20318_v1.0

**Comment by Voutsi** [comment]
Hi @jsitarek 

the production is ready. Test data are at
/fefs/aswg/data/mc/DL0/LSTProd2/TestDataset/sim_telarray/M20318

Training at 
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_2276/sim_telarray/M20318

and correspondingly for diffuse gammas

**Comment by jsitarek** [comment]
thanks a lot @Voutsi 
I'm starting to process those files with MCP

**Comment by jsitarek** [comment]
all those are finished (since 2023.07.31) 

/fefs/aswg/LST1MAGIC/mc/.../M20318A/NSBX.X/v01.3/dec_2276
