### ISSUE TITLE
LST1 telescope_transmission update

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/lst-sim-config#6]
In our standard Crab test sample (Nov-December 2020) muon ring analysis provides the best-match with simulations using 80% of the nominal telescope_transmission (i.e. just shadowing). But these data have ~5% of the mirror dish defocused.

~~We therefore propose to use as default 85% of the nominal telescope_transmission (0.9690).~~

So this means:

~~**telescope_transmission 0.8236**~~  (update on this below)

(finer adjustment at the percent level can be done in the calibration stage - and of course, re-running sim_telarray if needed, this is just a proposal for the default in the coming production)

**Comment by mexanick** [comment]
Out of curiosity, what was the reason of having 5% of mirrors defocused? And what's the current state of mirrors? Can we safely count that in normal operation conditions all (or almost all, say 99%) mirrors will be focused?

**Comment by moralejo** [comment]
I don't know the details, may be @satoshifukami0115 can comment. For some reason the mirrors could not be as accurately focused as the rest, and then it was deemed better to defocus them maximally (~1 deg away from the main spot, in six different directions).

**Comment by satoshifukami0115** [comment]
@mexanick The reason of 5% is that 10 mirrors out of 200 segmented mirrors were defocused from Nov. 2020 to Feb. 2021. The 200 mirrors were controlled by 16 PCs, and one of the PCs was not accessible unexpectedly during the period, which controls 9 mirrors (besides there is additional 1).

Please refer to page 9 of the daily AMC plots [here](https://www.lst1.iac.es/operations/amc/).
In the standard observations, the typical number of defocused mirrors is only a few (e.g. any day in Aug. 2021).
But I saw many defocused mirrors (>10) at some days in Sep. 2021, which is under investigation.

**Comment by moralejo** [comment]
Update: with lstchain 0.9 the calibration of data was revised, and results now in 2% lower charges.

Besides, since the first use of the new MC will be to analyse the existing LST1 data, we prefer to stick to the "80% efficiency" (relative to nominal MC), which would now be, with the 2% correction,  78.4%. Considering the shadowing factor, 0.9690, we should use:

`telescope_transmission 0.7597`

Which can anyway be tuned if needed) (at the few % level) at the (MC) analysis level, also to larger values - neglecting the small differences in signal fluctuations that a different efficiency would entail.

**Comment by moralejo** [comment]
Superseded by #23
