### ISSUE TITLE
Test production of declination line 6166 with very high density

### ISSUE THREAD

**Issue by gabemery** [cta-observatory/lst-sim-config#61]
This is to request a new production for the line 6166, **separated from current production for this dec line** if possible.

It will be a test production to evaluate the usability of a near continuous pointing in MC for the random forest training. It is thus limited to a small segment of the line.

You can find the positions in the attached file.  Total statistic for this segment should be the same as for the total of the three nodes it would replace in the current production.
[dec_6166_zenith_azimuth_grid_nearcontinuoustest.txt](https://github.com/cta-observatory/lst-sim-config/files/13055405/dec_6166_zenith_azimuth_grid_nearcontinuoustest.txt)

Corresponding to the new nodes in the following plot:
![image](https://github.com/cta-observatory/lst-sim-config/assets/35919817/8f8b5efb-687d-417d-84cc-c9bd9c7dab4e)

**Comment by Voutsi** [comment]
Hi @gabemery 

I can start the production sometime mid next week

**Comment by Voutsi** [comment]
Hi @gabemery,

the production has started. However please let me know if you prefer to fix issue #62 first or continue as usual. Thanks

**Comment by gabemery** [comment]
Hi @Voutsi , thank you. We can continue without fixing issue 62.

**Comment by Voutsi** [comment]
Hi @gabemery ,

the production is finished. You can find the data at:

/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6166/high_density_grid/sim_telarray

for gamma diffuse, and correspondingly for protons.

**Comment by jsitarek** [comment]
@gabemery,  this is only for LST1 or also for LST1+MAGIC? 
in the latter case, which MAGIC period are those?

**Comment by Voutsi** [comment]
Hi @jsitarek, maybe I should reply since I launched this production: It is LST1+MAGIC, and I used the ST0316 MAGIC period.

**Comment by jsitarek** [comment]
thanks @Voutsi for a quick reply. 
if those are to be processed as well with MCP part I still need to do it.

**Comment by gabemery** [comment]
@jsitarek No need for you to do it. I can process it myself when needed.
