### ISSUE TITLE
Declination band 34.76 with ST0320 settings

### ISSUE THREAD

**Issue by Voutsi** [cta-observatory/lst-sim-config#69]
Reprocessing of the training datasets of declination band 34.76 with the ST0320 settings

**Comment by Voutsi** [comment]
Hi @jsitarek 

The simtel production has finished. You can fine the data for e.g. protons at:

/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_3476/sim_telarray/ST0320

**Comment by jsitarek** [comment]
thanks! I started running the DL1 files

**Comment by jsitarek** [comment]
the train files are processed up to DL1Stereo level:
/fefs/aswg/LST1MAGIC/mc/special/20231215_ctapipe0.19/DL1Stereo/ST0320A/NSB*/*/v02.0/dec_3476
