### ISSUE TITLE
MAGIC PSF and reflectivity retuning

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/lst-sim-config#7]
The previous MAGIC settings in MAGIC+LST1 MCs were using MAGIC analysis period ST.03.07, while the current one is ST.03.16, the differences are in the PSF and reflectivity (mostly M1). 

1)  "Mirror fraction" in MAGIC simulations is 0.61 in M1 and 0.69 in M2, however the earlier tuning to sim_telarray showed that you need ~8% lower reflectivity values in sim_telarray to match the MAGIC standard MCs, hence those are the expected settings:
telescope_transmission = 0.561 (M1)
telescope_transmission = 0.635 (M2)

2) PSF is more tricky, and was retunned by hand using MARS cermaker and "stars" option in sim_telarray to simulate a point-like light source and match the PSF parameters by hand, those are the optimized settings:

% M1 optimal settings for ST0316
   random_focal_length = 0
   mirror_reflection_random_angle = 0.020,0.2,0.115
   mirror_align_random_distance = 0.0 % cm
   mirror_align_random_horizontal = 0.015,28.,0.0,0.0
   mirror_align_random_vertical = 0.015,28.,0.0,0.0

% M2 optimal settings (for both ST0307 and ST0316)
random_focal_length = 0
mirror_reflection_random_angle = 0.012,0.23,0.15
mirror_align_random_distance = 0.0 % cm
mirror_align_random_horizontal = 0.014,28.,0.0,0.0
mirror_align_random_vertical = 0.014,28.,0.0,0.0

![magic_psf_comparison](https://user-images.githubusercontent.com/33022433/145417403-25279b16-52fc-41fa-bcbc-86990549ddad.png)

**Comment by YoshikiOhtani** [comment]
Apologies for being late, but I have just pushed the new MAGIC configuration files (LST-PROD2-MAGIC1.cfg, LST-PROD2-MAGIC2.cfg) to the "sim-telarray" branch. The mirror settings and the telescope transmission are updated to the ones provided by Julian for ST.03.16.

**Comment by jsitarek** [comment]
Thank you Yoshiki!
going through the input card I think it can be further cleaned 
I'm not sure what is #ifdef LST_INTERMEDIATE_SHAPE, but probably you can keep only this line:
dish_shape_length   = 1697

**Comment by jsitarek** [comment]
as with other parameters, the PSF and reflectivity can be further tunned with muons, but the current settings should not be much off, closing issue
