### ISSUE TITLE
Removal of low gain in MAGIC part of simulations

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/lst-sim-config#8]
The original MAGIC+LST1 simulations were heavily based on copying things from LST1, and for simplicity two gains were kept, which is not needed - MAGIC readout is using only a single gain for each channel

**Comment by moralejo** [comment]
@jsitarek or @YusukeSuda , can you write out explicitly what would be the sim_telarray settings with just one gain?

**Comment by YusukeSuda** [comment]
Hi @moralejo , I think we can realize it by changing "num_gain" and removing the relevant low gain parameters out in "CTA-PROD4-MAGIC1(2)_test.cfg" file.

***
fadc_pedestal = 300           % Per time slice (positive signals only: unsigned!)
fadc_amplitude = 40.0        % The peak amplitude in a time slice for high gain.
fadc_noise = 12.0                 % Again per time slice (high gain).

num_gains = 1                      % Make it clear that we want to use one gain
% fadc_lg_pedestal = 300    % Per time slice (positive signals only: unsigned!)
% fadc_lg_amplitude = 2.2    % The peak amplitude in a time slice for low gain (HG/LG=18 ??)
% fadc_lg_noise = 2.2            % Again per time slice (low gain).
***

**Comment by mexanick** [comment]
Actually, the MAGIC configuration files are currently taken from what is served with the sim_telarray distribution and are not included in the list of files which is currently available under sim_telarray branch. So after we know exactly, what should be MAGIC configurations, I believe we need to ask someone knowledgeable (@jsitarek or @YusukeSuda or someone else?) to create MAGIC config files and add them to the sim_telarray branch

**Comment by moralejo** [comment]
@YusukeSuda please cross-check also with @jsitarek that the actual baseline, amplitude and noise in the single MAGIC gain branch are the right ones.

**Comment by jsitarek** [comment]
Hi, sorry for a delayed answer. for sure you need to at least increase the saturation value, the current one in the file is fadc_max_signal = 4095, and baseline is set at 300, so saturation is 3795 above the baseline.
In MAGIC simulations the saturation is 13500 above the baseline, so I think you should put 
fadc_max_signal = 13800 
I will double check the rest of the readout parameters and let you know.

**Comment by jsitarek** [comment]
Hi, I checked the ADC parameters and they actually seam to be quite off the values that we use in the camera simulation (in particular the pulse shape). Please find attached a few slides summarizing those studies
[20220103_magic_readout_settings.pdf](https://github.com/cta-observatory/lst-sim-config/files/7801866/20220103_magic_readout_settings.pdf)

EDIT: I generated some single phe pulses with sim_telarray and with MAGIC camera simulator. In red is the original one, in blue I tuned it following the numbers in the pdf file above. After tuning the match is much better, but there is still a bit of difference, this might be because of the simulation of fluctuations, or because of the way how in MAGIC camera the pulse integral is converted into the amplitude. I will check the latter one to see if the match is better and then make new files with updated readout settings. 

Note that the pulse shapes of the trigger would likely also have to be updated, but this is very difficult to check properly.
![single_phe_sim_telarray_vs_camera](https://user-images.githubusercontent.com/33022433/147962084-344d93d0-ea01-49a5-994d-16c60feecba6.png)

**Comment by moralejo** [comment]
Thanks @jsitarek! Strange, anyone knows where that very broad pulse may have come from?

**Comment by jsitarek** [comment]
this file: pulse_CTA-Fx3.dat is used in CTA-PROD4-LST.cfg and CTA-PROD4-MST-NectarCam.cfg
however in the current LST settings it seems to be updated to the Yukiho's measurement from last year

**Comment by jsitarek** [comment]
the updated readout settings were put in PR #13
