### ISSUE TITLE
Telescope coordinates

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/lst-sim-config#9]
For a LST1 + M1 + M2 production I think we should not center the array at the average coordinates, because LST1 with its larger mirror will have larger reach in impact. I propose to define the center at the dish-area-weighted average (assuming just circular dishes of 17m and 23m diameter) of the three telescopes - actually this only brings it a bit closer to LST1:

![image](https://user-images.githubusercontent.com/14164282/145464345-575f5d6c-61e3-48ed-9b26-316d00e9fdec.png)

I would also redefine the observation level (@YusukeSuda, was there any reason to keep the same OBSLEV of the full CTA-N production for the LST-MAGIC dedicated productions?)

The values for the Corsika input card (x=north, y=west) would be these ones (a crosscheck is welcome):

```
OBSLEV 2199E2

TELESCOPE              -6.336E2    60.405E2   2.00E2        12.50E2   # L-01     (ID=1)
TELESCOPE              41.054E2   -79.275E2   0.25E2        10.00E2   # MAGIC-01 (ID=2)
TELESCOPE             -29.456E2   -31.295E2   1.42E2        10.00E2   # MAGIC-02 (ID=3)
```

**Comment by moralejo** [comment]
### Related changes in sim_telarray configuration:

- **ALTITUDE** should also be changed to **2199** (although this is just for atmospheric profile purposes so the difference will be negligible). 
- **REFERENCE_POSITION 0  0  1.36E2**      (just weighted average of z-positions). It is used for calculation of impact parameter "w.r.t. the array"
- Raised by @YoshikiOhtani : do we need to change PHOTON_DELAY for the telescopes, given the change in OBSLEV??

**Comment by jsitarek** [comment]
About the altitude - this might also affect the Hmax calculation slightly (I'm not sure if the value used is above the see level or about ground, but either way needs to be propagated consistently between the data and MCs.

**Comment by moralejo** [comment]
> About the altitude - this might also affect the Hmax calculation slightly (I'm not sure if the value used is above the see level or about ground, but either way needs to be propagated consistently between the data and MCs.

In any case, having a consistent value between Corsika and sim_telarray seems the way to go, right?

@jsitarek, can you shed some light on the PHOTON_DELAY parameter? I think it affects the position of the pulses in the readout window, but it should _not_ change with the change of OBSLEV. @YoshikiOhtani  is afraid that it might be needed, though.

**Comment by YoshikiOhtani** [comment]
Hi, regarding the Hmax, if one uses the ctapipe module (HillasReconstructor in case of ctapipe v0.8.0) the Hmax can be calculated from any altitudes - I mean one needs to input the telescope positions (x, y, z) defined in a given coordinate (sea level or observation level, whatever) and the Hmax parameter is calculated based on the coordinate. I actually use the coordinate with respect to the observation level for the combined analysis. 

Then regarding the photon_delay, actually I was looking back to the past studies, but eventually I could not figure out if changing the observation level affects the timing of the trigger pulse... I thought that the starting time of the trigger simulation depends on the observation level, but I'm not 100% sure... probably @YusukeSuda remembers about this, so I would like to ask his opinion on this. Anyway if the OBSLEV affects the timing of the trigger pulse, it can be adjusted in sim_telarray config and so I would say there is no problem of producing the CORSIKA data with changed OBSLEV.

**Comment by jsitarek** [comment]
concerning the PHOTON_DELAY, I would be very surprised if this needs to be updated. this part of sim_telarray looks a bit obscure to me, but the time delays seems to be computed w.r.t. median time of the phe that arrive in the telescope (with some extra shifts e.g. for a fraction of a FADC window).

**Comment by YusukeSuda** [comment]
OBSLEV - I am not aware of any reason to keep the same value of the full CTA-N production for the LST-MAGIC dedicated productions

ALTITUDE - I also think this should be the same as OBSLEV. @jsitarek , this value is above sea level.

PHOTON_DELAY - We don't need to change this value. Just in case I have looked at the codes and just confirmed what @jsitarek wrote :)
